networks:
    laravel:
        driver: bridge

volumes:
    mysql-data:

services:
    app:
        build: .
        volumes:
            - ./:/var/www
        networks:
            - laravel
        depends_on:
            - mysql
            - redis

    supervisor:
        build:
            context: .
            dockerfile: docker/supervisor/Dockerfile
        restart: unless-stopped
        volumes:
            - .:/var/www
        depends_on:
            - app
            - redis
        networks:
            - laravel

    webserver:
        image: nginx:alpine
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/conf.d:/etc/nginx/conf.d
        depends_on:
            - app
        networks:
            - laravel

    mysql:
        image: mysql:8.0
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:?}
            MYSQL_DATABASE: ${DB_DATABASE:?}
            MYSQL_USER: ${DB_USERNAME:?}
            MYSQL_PASSWORD: ${DB_PASSWORD:?}
        ports:
            - "3306:3306"
        volumes:
            - mysql-data:/var/lib/mysql
        networks:
            - laravel

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        restart: always
        environment:
            PMA_HOST: mysql
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:?}
        ports:
            - "8080:80"
        networks:
            - laravel

    redis:
        image: redis:alpine
        ports:
            - "6379:6379"
        networks:
            - laravel

    redisinsight:
        image: redislabs/redisinsight:latest
        ports:
            - "5540:5540"
        networks:
            - laravel

    mailpit:
        image: axllent/mailpit
        container_name: mailpit
        restart: unless-stopped
        volumes:
        - ./data:/data
        ports:
        - 8025:8025
        - 1025:1025
        environment:
            MP_MAX_MESSAGES: 5000
            MP_DATABASE: /data/mailpit.db
            MP_SMTP_AUTH_ACCEPT_ANY: 1
            MP_SMTP_AUTH_ALLOW_INSECURE: 1
        networks:
            - laravel
